FROM python:3.12.3-slim

RUN apt-get update && \
    apt-get install -y gcc libpq-dev && \
    apt clean && \
    rm -rf /var/cache/apt/*

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONIOENCODING=utf-8

COPY requirements.txt /tmp/requirements.txt

RUN pip install -U pip && \
    pip install --no-cache-dir -r /tmp/requirements.txt

COPY . /finefind

ENV PATH "$PATH:/finefind/scripts"

RUN useradd -m -d /finefind -s /bin/bash app \
    && chown -R app:app /finefind && chmod +x /finefind/scripts/*

WORKDIR /finefind
USER app

CMD ["./scripts/start-dev.sh"]