services:
  app:
    container_name: app
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
      - 5678:5678
    volumes:
      - ./app:/finefind/app
      - ./scripts:/finefind/scripts
      - ./alembic:/finefind/alembic
      - ./alembic.ini:/finefind/alembic.ini
      - ./pyproject.toml:/finefind/pyproject.toml
      - ./tests:/finefind/tests
    depends_on:
      - postgres
      - redis

  postgres:
    container_name: postgres
    hostname: app_db
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - app_pg_data:/var/lib/postgresql/data
      - app_pg_data_backups:/backups
      - ./scripts/postgres:/scripts

  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    command:
      - 'redis-server'
      - '--requirepass password'
    ports:
      - "6379:6379"

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  app_pg_data:
    driver: "local"
  app_pg_data_backups:
    driver: "local"

networks:
  default:
    external: true
    name: app_network
